[package]
name = "visual-jib-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
jib = { path = "../jib", version = "*" }
jib-asm = { path = "../jib-asm", version = "*" }
cbuoy = { path = "../cbuoy", version = "*" }

[build-dependencies]
cbuoy = { path = "../cbuoy", version = "*" }
